### ISSUE TITLE
Faltam campos para criação de usuário.

### ISSUE THREAD

**Issue by yagolasse** [mvfsilva/projeto-integrador#5]
É necessário adicionar campos para usuário, senha e etc no mesmo form que cadastra ONG. Recomendo também que seja feito em uma tela separada, para que seja possível editar/apagar/detalhar a ONG.

**Comment by mvfsillva** [comment]
Pensei em criar um botão chamado detalhes, e lá ter o direcionamento das telas para edição, etc ...O que acham? 
Sobre os campos irei adicionar no modal!

**Comment by yagolasse** [comment]
Eu adicionei no próprio form de ONG o campo de senha, para facilitar. E estava pensando em utilizar o próprio modal para mostrar os detalhes. Já mudei a lista de ongs para mostrar a área de atuação.
